version: '3.8'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pcmarket
      MYSQL_ROOT_PASSWORD: market
    ports:
      - '3307:3306'
    volumes:
      - ../.mysql:/var/lib/mysql