version: '3.8'

services:
  market-db:
    container_name: market-database
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: market
      MYSQL_ROOT_PASSWORD: market
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - ../.mysql:/var/lib/mysql